//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartVideo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaginatedFilm", ReplyAction="http://tempuri.org/IService1/GetPaginatedFilmResponse")]
        DTO.FilmCompletDTO[] GetPaginatedFilm(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaginatedFilm", ReplyAction="http://tempuri.org/IService1/GetPaginatedFilmResponse")]
        System.Threading.Tasks.Task<DTO.FilmCompletDTO[]> GetPaginatedFilmAsync(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilm", ReplyAction="http://tempuri.org/IService1/GetFilmResponse")]
        DTO.FilmCompletDTO GetFilm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilm", ReplyAction="http://tempuri.org/IService1/GetFilmResponse")]
        System.Threading.Tasks.Task<DTO.FilmCompletDTO> GetFilmAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SmartVideo.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SmartVideo.ServiceReference1.IService1>, SmartVideo.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DTO.FilmCompletDTO[] GetPaginatedFilm(int page) {
            return base.Channel.GetPaginatedFilm(page);
        }
        
        public System.Threading.Tasks.Task<DTO.FilmCompletDTO[]> GetPaginatedFilmAsync(int page) {
            return base.Channel.GetPaginatedFilmAsync(page);
        }
        
        public DTO.FilmCompletDTO GetFilm(int id) {
            return base.Channel.GetFilm(id);
        }
        
        public System.Threading.Tasks.Task<DTO.FilmCompletDTO> GetFilmAsync(int id) {
            return base.Channel.GetFilmAsync(id);
        }
    }
}
